[package]
name = "cmuxd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cmuxd"
path = "src/main.rs"

[dependencies]
cmux-proto = { path = "../cmux-proto" }
alacritty_terminal = { workspace = true }
anyhow = { workspace = true }
portable-pty = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
